# Generated by Django 5.1.6 on 2025-02-27 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empleo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("requisitos", models.TextField()),
                ("tipo_contrato", models.CharField(max_length=100)),
                ("salario", models.CharField(blank=True, max_length=100, null=True)),
                ("ubicacion", models.CharField(max_length=200)),
                ("fecha_publicacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SolicitudEmpleo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_apellidos", models.CharField(max_length=200)),
                ("telefono", models.CharField(max_length=15)),
                ("correo_electronico", models.EmailField(max_length=254)),
                ("direccion", models.TextField()),
                ("titulos", models.TextField()),
                ("experiencia_profesional", models.TextField()),
                ("estudios_posgrado", models.TextField(blank=True, null=True)),
                ("proyectos_investigacion", models.TextField(blank=True, null=True)),
                ("publicaciones", models.TextField(blank=True, null=True)),
                ("eventos", models.TextField(blank=True, null=True)),
                ("otras_actividades", models.TextField(blank=True, null=True)),
                (
                    "curriculum",
                    models.FileField(blank=True, null=True, upload_to="curriculums/"),
                ),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
                (
                    "empleo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes",
                        to="empleos.empleo",
                    ),
                ),
            ],
        ),
    ]
