# Generated by Django 5.1.6 on 2025-02-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleo",
            name="area",
            field=models.CharField(
                choices=[
                    ("ciencia", "Ciencia"),
                    ("medio_ambiente", "Medio Ambiente"),
                    ("gestion_documental", "Gestión Documental"),
                    ("administracion", "Administración"),
                ],
                default=2,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
