# Generated by Django 5.1.5 on 2025-03-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleos", "0002_empleo_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleo",
            name="area",
            field=models.CharField(
                choices=[
                    ("direccion", "Dirección"),
                    ("ciencia", "Ciencia, Tecnología e Innovación"),
                    ("medio_ambiente", "Medio Ambiente"),
                    ("gestion_documental", "Gestión Documental"),
                    ("administracion", "Administración"),
                ],
                max_length=50,
            ),
        ),
    ]
