# Generated by Django 5.1.4 on 2025-04-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0003_alter_empleo_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleo',
            name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='empleo',
            name='requisitos',
        ),
        migrations.AddField(
            model_name='empleo',
            name='documento_detalles',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
