# Generated by Django 5.1.4 on 2025-05-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0004_remove_empleo_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
