# Generated by Django 5.1.4 on 2025-05-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0005_empleo_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudempleo',
            name='revisado',
            field=models.BooleanField(default=False),
        ),
    ]
