# Generated by Django 5.1.4 on 2025-05-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0006_solicitudempleo_revisado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleo',
            name='documento_detalles',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
