# Generated by Django 5.1.4 on 2025-03-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_calificacion_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
