# Generated by Django 5.1.4 on 2025-03-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_calificacion_hora_creacion_comentario_hora_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='estrellas',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Calificacion',
        ),
    ]
