# Generated by Django 5.1.4 on 2025-03-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_comentario_estrellas_alter_comentario_texto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(max_length=50)),
                ('enlace', models.URLField()),
            ],
        ),
    ]
