# Generated by Django 5.1.4 on 2025-03-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlaceUtil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('logo', models.ImageField(help_text='Logo del sitio (recomendado: 200x200 px).', upload_to='enlaces_utiles/')),
            ],
        ),
    ]
