# Generated by Django 5.1.4 on 2025-05-21 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_enlaceutil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('title', 'Título'), ('text', 'Texto'), ('image', 'Imagen')], max_length=10)),
                ('contenido', models.TextField()),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.noticia')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('noticia', 'orden')},
            },
        ),
    ]
