# Generated by Django 5.1.4 on 2025-06-23 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bloque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='noticia',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='padre',
        ),
        migrations.DeleteModel(
            name='Bloque',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Noticia',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
