# Generated by Django 5.1.4 on 2025-06-23 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_noticias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='texto_completo',
        ),
    ]
