# Generated by Django 5.1.4 on 2025-06-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_noticias', '0002_remove_post_texto_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='vistas',
            field=models.IntegerField(default=0),
        ),
    ]
