# Generated by Django 5.1.6 on 2025-02-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Queja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_apellidos", models.CharField(max_length=200)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("categoria1", "Categoría 1"),
                            ("categoria2", "Categoría 2"),
                            ("categoria3", "Categoría 3"),
                        ],
                        max_length=50,
                    ),
                ),
                ("telefono_movil", models.CharField(max_length=15)),
                (
                    "telefono_fijo",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("correo_electronico", models.EmailField(max_length=254)),
                ("direccion", models.TextField()),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("asunto", models.TextField()),
                (
                    "evidencias",
                    models.FileField(blank=True, null=True, upload_to="evidencias/"),
                ),
            ],
        ),
    ]
