# Generated by Django 5.1.5 on 2025-03-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atencion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="queja",
            name="estado",
            field=models.CharField(default="En proceso", max_length=50),
        ),
        migrations.AddField(
            model_name="queja",
            name="id_queja",
            field=models.CharField(
                default=1, editable=False, max_length=8, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="queja",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("servicio", "Servicio"),
                    ("infraestructura", "Infraestructura"),
                    ("otros", "Otros"),
                ],
                max_length=50,
            ),
        ),
    ]
