# Generated by Django 5.0.3 on 2025-02-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nosotros', '0002_delete_informacioninstitucional'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Directivo',
        ),
    ]
